package cold.face.dal.model;

public class GoodsNumber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_number.goods_id
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_number.goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    private Integer goodsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_number.goods_id
     *
     * @return the value of t_goods_number.goods_id
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_number.goods_id
     *
     * @param goodsId the value for t_goods_number.goods_id
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_number.goods_number
     *
     * @return the value of t_goods_number.goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_number.goods_number
     *
     * @param goodsNumber the value for t_goods_number.goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }
}