package cold.face.dal.model;

public class NoodlesType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noodles_type.id
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noodles_type.type_code
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noodles_type.name
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noodles_type.parent_type_code
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    private String parentTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noodles_type.remark
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noodles_type.id
     *
     * @return the value of noodles_type.id
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noodles_type.id
     *
     * @param id the value for noodles_type.id
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noodles_type.type_code
     *
     * @return the value of noodles_type.type_code
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noodles_type.type_code
     *
     * @param typeCode the value for noodles_type.type_code
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noodles_type.name
     *
     * @return the value of noodles_type.name
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noodles_type.name
     *
     * @param name the value for noodles_type.name
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noodles_type.parent_type_code
     *
     * @return the value of noodles_type.parent_type_code
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public String getParentTypeCode() {
        return parentTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noodles_type.parent_type_code
     *
     * @param parentTypeCode the value for noodles_type.parent_type_code
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public void setParentTypeCode(String parentTypeCode) {
        this.parentTypeCode = parentTypeCode == null ? null : parentTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noodles_type.remark
     *
     * @return the value of noodles_type.remark
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noodles_type.remark
     *
     * @param remark the value for noodles_type.remark
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}