package cold.face.dal.dao;

import cold.face.dal.model.GoodsNumber;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

public interface GoodsNumberDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    int insert(GoodsNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    int insertSelective(GoodsNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    GoodsNumber selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_number
     *
     * @mbg.generated Thu Apr 29 15:34:31 CST 2021
     */
    int updateByPrimaryKey(GoodsNumber record);

    @Transactional(readOnly = false, propagation = Propagation.SUPPORTS)
    int countDownGoodsNumber(GoodsNumber goodsNumber);
}