package cold.face.dal.dao;

import cold.face.dal.model.Noodles;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface NoodlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int insert(Noodles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int insertSelective(Noodles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    Noodles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int updateByPrimaryKeySelective(Noodles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Noodles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int updateByPrimaryKey(Noodles record);
}