package cold.face.dal.dao;

import cold.face.dal.model.NoodlesType;

import java.util.List;

public interface NoodlesTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int insert(NoodlesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int insertSelective(NoodlesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    NoodlesType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int updateByPrimaryKeySelective(NoodlesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NoodlesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noodles_type
     *
     * @mbg.generated Wed Jul 18 09:50:24 CST 2018
     */
    int updateByPrimaryKey(NoodlesType record);

    List<NoodlesType> getAllNoodlesType();
}